package com.codefest.api.hotel;

import java.math.BigDecimal;
import java.util.List;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class HotelSeeder implements CommandLineRunner {
  private final HotelRepository hotelRepository;

  public HotelSeeder(HotelRepository hotelRepository) {
    this.hotelRepository = hotelRepository;
  }

  @Override
  public void run(String... args) {
    seedHotels()
        .forEach(
            hotel -> {
              if (!hotelRepository.existsByNameIgnoreCaseAndCityIgnoreCase(hotel.name(), hotel.city())) {
                hotelRepository.save(
                    new Hotel(
                        hotel.name(),
                        hotel.city(),
                        hotel.country(),
                        hotel.description(),
                        hotel.nightlyRate(),
                        hotel.currency(),
                        hotel.availableRooms()));
              }
            });
  }

  private List<SeedHotel> seedHotels() {
    return List.of(
        new SeedHotel(
            "North Loop House",
            "Minneapolis",
            "US",
            "Modern downtown hotel near restaurants, transit, and event venues.",
            new BigDecimal("189.00"),
            "USD",
            12),
        new SeedHotel(
            "Riverfront Suites",
            "Chicago",
            "US",
            "Suite-focused hotel with skyline views and quick access to the riverwalk.",
            new BigDecimal("249.00"),
            "USD",
            8),
        new SeedHotel(
            "Capitol Garden Inn",
            "Austin",
            "US",
            "Quiet boutique hotel with meeting rooms and a courtyard workspace.",
            new BigDecimal("159.00"),
            "USD",
            10),
        new SeedHotel(
            "Harbor Light Hotel",
            "Seattle",
            "US",
            "Waterfront hotel with meeting suites, ferry access, and mountain views.",
            new BigDecimal("229.00"),
            "USD",
            9),
        new SeedHotel(
            "Mission Bay Lodge",
            "San Francisco",
            "US",
            "Compact business hotel near transit, medical offices, and waterfront trails.",
            new BigDecimal("279.00"),
            "USD",
            6),
        new SeedHotel(
            "Union Square Grand",
            "New York",
            "US",
            "Full-service hotel with flexible workspaces and quick subway access.",
            new BigDecimal("319.00"),
            "USD",
            11),
        new SeedHotel(
            "Peachtree Commons",
            "Atlanta",
            "US",
            "Downtown hotel with conference rooms and easy airport rail connections.",
            new BigDecimal("174.00"),
            "USD",
            14),
        new SeedHotel(
            "Back Bay Terrace",
            "Boston",
            "US",
            "Neighborhood hotel near offices, restaurants, and riverfront running paths.",
            new BigDecimal("264.00"),
            "USD",
            7),
        new SeedHotel(
            "Cherry Creek Station",
            "Denver",
            "US",
            "Modern stay with coworking areas, mountain shuttles, and secure parking.",
            new BigDecimal("205.00"),
            "USD",
            13),
        new SeedHotel(
            "Arts District Hotel",
            "Los Angeles",
            "US",
            "Design-forward hotel near galleries, dining, and downtown event venues.",
            new BigDecimal("238.00"),
            "USD",
            8),
        new SeedHotel(
            "Biscayne Palm Resort",
            "Miami",
            "US",
            "Bright resort-style hotel with pool deck, meeting cabanas, and bay access.",
            new BigDecimal("221.00"),
            "USD",
            15),
        new SeedHotel(
            "Music Row Suites",
            "Nashville",
            "US",
            "Suite hotel close to studios, restaurants, and small event spaces.",
            new BigDecimal("183.00"),
            "USD",
            10),
        new SeedHotel(
            "Ocean Two Resort & Residences",
            "Barbados",
            "BB",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("389.00"),
            "USD",
            18),
        new SeedHotel(
            "Heywoods Park Holiday Rental",
            "Speightstown",
            "BB",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("419.00"),
            "USD",
            16),
        new SeedHotel(
            "Coral Sands Beach Resort",
            "Bridgetown",
            "BB",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("449.00"),
            "USD",
            14),
        new SeedHotel(
            "Zion Country Eco Beach Cabins",
            "Portland, Jamaica W.I.",
            "JM",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("359.00"),
            "USD",
            22),
        new SeedHotel(
            "Goblin Hill Villas at San San",
            "Port Antonio",
            "JM",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("389.00"),
            "USD",
            20),
        new SeedHotel(
            "Strawberry Hill Resort",
            "Irish Town",
            "JM",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("419.00"),
            "USD",
            18),
        new SeedHotel(
            "Sugar Beach, A Viceroy Resort",
            "La Baie de Silence, Soufriere",
            "LC",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("439.00"),
            "USD",
            14),
        new SeedHotel(
            "Fond Bay Suites and Villa",
            "Micoud",
            "LC",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("469.00"),
            "USD",
            12),
        new SeedHotel(
            "Tet Rouge Resort",
            "Choiseul",
            "LC",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("499.00"),
            "USD",
            10),
        new SeedHotel(
            "One And Only Ocean Club",
            "Paradise Island",
            "BS",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("329.00"),
            "USD",
            24),
        new SeedHotel(
            "Crooked Island Lodge",
            "Pitts Town",
            "BS",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("359.00"),
            "USD",
            22),
        new SeedHotel(
            "Royal Islander Hotel",
            "Freeport",
            "BS",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("389.00"),
            "USD",
            20),
        new SeedHotel(
            "Caribbean Palm Village Resort",
            "Noord",
            "AW",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("369.00"),
            "USD",
            20),
        new SeedHotel(
            "Renaissance Marina Tower",
            "Oranjestad",
            "AW",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("399.00"),
            "USD",
            18),
        new SeedHotel(
            "La Quinta Beach Resort",
            "Noord",
            "AW",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("429.00"),
            "USD",
            16),
        new SeedHotel(
            "Blue Haven Resort – All-Inclusive",
            "Providenciales",
            "TC",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("519.00"),
            "USD",
            12),
        new SeedHotel(
            "Alexandra Resort - All-Inclusive",
            "Grace Bay",
            "TC",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("549.00"),
            "USD",
            10),
        new SeedHotel(
            "Happy House Villa",
            "Grace Bay Hills",
            "TC",
            "Beachfront resort with palm-shaded pool deck, snorkel access, and breezy oceanview rooms.",
            new BigDecimal("579.00"),
            "USD",
            8),
        new SeedHotel(
            "Amilla Fushi Maldives Resort and Residences",
            "Male",
            "MV",
            "Overwater bungalows above a coral lagoon, with private decks and direct reef access.",
            new BigDecimal("869.00"),
            "USD",
            8),
        new SeedHotel(
            "Four Seasons Resort",
            "Landaa Giraavaru",
            "MV",
            "Overwater bungalows above a coral lagoon, with private decks and direct reef access.",
            new BigDecimal("899.00"),
            "USD",
            6),
        new SeedHotel(
            "Planktons Beach",
            "Hulhumale",
            "MV",
            "Overwater bungalows above a coral lagoon, with private decks and direct reef access.",
            new BigDecimal("929.00"),
            "USD",
            4),
        new SeedHotel(
            "Hôtel Costes",
            "Paris",
            "FR",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("259.00"),
            "EUR",
            16),
        new SeedHotel(
            "Timhôtel Best Western Tour Eiffel Invalides",
            "Paris",
            "FR",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("289.00"),
            "EUR",
            14),
        new SeedHotel(
            "Hôtel de la Place des Vosges",
            "Paris",
            "FR",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("319.00"),
            "EUR",
            12),
        new SeedHotel(
            "Istituto Maria Santissima Bambina",
            "Roma",
            "IT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("219.00"),
            "EUR",
            18),
        new SeedHotel(
            "Domus Pacis Torre Rossa Park",
            "Roma",
            "IT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("249.00"),
            "EUR",
            16),
        new SeedHotel(
            "Marriott Grand Flora Hotel",
            "Roma",
            "IT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("279.00"),
            "EUR",
            14),
        new SeedHotel(
            "La Mola Hotel & Conference Centre",
            "Terrassa",
            "ES",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("199.00"),
            "EUR",
            20),
        new SeedHotel(
            "ibis Barcelona Meridiana",
            "Barcelona",
            "ES",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("229.00"),
            "EUR",
            18),
        new SeedHotel(
            "Rafael Hoteles Badalona",
            "Badalona",
            "ES",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("259.00"),
            "EUR",
            16),
        new SeedHotel(
            "NH Collection Amsterdam Barbizon Palace",
            "Amsterdam",
            "NL",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("279.00"),
            "EUR",
            14),
        new SeedHotel(
            "Anantara Grand Hotel Krasnapolsky",
            "Amsterdam",
            "NL",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("309.00"),
            "EUR",
            12),
        new SeedHotel(
            "Clayton Hotel Amsterdam American",
            "Amsterdam",
            "NL",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("339.00"),
            "EUR",
            10),
        new SeedHotel(
            "Hotel Ibis Lisboa José Malhoa",
            "Lisboa",
            "PT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("169.00"),
            "EUR",
            18),
        new SeedHotel(
            "Hotel Eurostars Lisboa Parque",
            "Lisboa",
            "PT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("199.00"),
            "EUR",
            16),
        new SeedHotel(
            "VIP Executive Saldanha Hotel",
            "Lisboa",
            "PT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("229.00"),
            "EUR",
            14),
        new SeedHotel(
            "Prague City Stay Jagellonská ApartHotel",
            "Praha 3",
            "CZ",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("139.00"),
            "EUR",
            20),
        new SeedHotel(
            "Hotel Meda of Museum Kampa",
            "Praha 6",
            "CZ",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("169.00"),
            "EUR",
            18),
        new SeedHotel(
            "The Mozart Prague",
            "Praha",
            "CZ",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("199.00"),
            "EUR",
            16),
        new SeedHotel(
            "Mercure Grand Hotel Biedermeier Wien",
            "Wien",
            "AT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("189.00"),
            "EUR",
            16),
        new SeedHotel(
            "Hotel IMLAUER & Nestroy Wien",
            "Wien",
            "AT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("219.00"),
            "EUR",
            14),
        new SeedHotel(
            "Kyriad Vienna Altmannsdorf",
            "Wien",
            "AT",
            "Boutique city hotel near historic landmarks, cafes, and metro lines.",
            new BigDecimal("249.00"),
            "EUR",
            12),
        new SeedHotel(
            "Meli Meli Accommodation",
            "Santorini",
            "GR",
            "Cliffside whitewashed suites with caldera views, infinity pool, and sunset terrace.",
            new BigDecimal("349.00"),
            "EUR",
            10),
        new SeedHotel(
            "Hotel Mathios Village",
            "Akrotiri",
            "GR",
            "Cliffside whitewashed suites with caldera views, infinity pool, and sunset terrace.",
            new BigDecimal("379.00"),
            "EUR",
            8),
        new SeedHotel(
            "Hotel Veggera",
            "Perissa Santorini",
            "GR",
            "Cliffside whitewashed suites with caldera views, infinity pool, and sunset terrace.",
            new BigDecimal("409.00"),
            "EUR",
            6),
        new SeedHotel(
            "Temptation Resort Spa Cancun",
            "Cancun",
            "MX",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("239.00"),
            "USD",
            22),
        new SeedHotel(
            "GR Caribe Deluxe By Solaris",
            "Cancún",
            "MX",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("269.00"),
            "USD",
            20),
        new SeedHotel(
            "Omni Cancun Hotel & Villas",
            "Cancún",
            "MX",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("299.00"),
            "USD",
            18),
        new SeedHotel(
            "Hotel Hacienda Cobá",
            "Cobá",
            "MX",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("299.00"),
            "USD",
            12),
        new SeedHotel(
            "Maya Tulum",
            "Tulum",
            "MX",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("329.00"),
            "USD",
            10),
        new SeedHotel(
            "Akumal Bay Beach & Wellness Resort",
            "Tulum",
            "MX",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("359.00"),
            "USD",
            8),
        new SeedHotel(
            "The Westin Resort & Spa Ubud, Bali",
            "Ubud",
            "ID",
            "Jungle-canopy retreat with open-air pavilions, plunge pools, and rice-paddy views.",
            new BigDecimal("189.00"),
            "USD",
            14),
        new SeedHotel(
            "Cendana Resort & Spa",
            "Ubud",
            "ID",
            "Jungle-canopy retreat with open-air pavilions, plunge pools, and rice-paddy views.",
            new BigDecimal("219.00"),
            "USD",
            12),
        new SeedHotel(
            "The Sungu Resort",
            "Penestenan",
            "ID",
            "Jungle-canopy retreat with open-air pavilions, plunge pools, and rice-paddy views.",
            new BigDecimal("249.00"),
            "USD",
            10),
        new SeedHotel(
            "Hotel The Royal Beach Seminyak Bali - Mgallery Collection",
            "Seminyak, Kuta, Bali",
            "ID",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("169.00"),
            "USD",
            18),
        new SeedHotel(
            "Ramada Bali Sunset Road Kuta",
            "Kuta, Bali",
            "ID",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("199.00"),
            "USD",
            16),
        new SeedHotel(
            "Harris Hotel Seminyak - Bali",
            "Seminyak, Kuta, Badung, Bali",
            "ID",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("229.00"),
            "USD",
            14),
        new SeedHotel(
            "Ohia Waikiki Studio Suites",
            "Honolulu",
            "US",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("319.00"),
            "USD",
            20),
        new SeedHotel(
            "The Imperial Hawaii Resort",
            "Honolulu",
            "US",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("349.00"),
            "USD",
            18),
        new SeedHotel(
            "Airport Honolulu Hotel",
            "Honolulu",
            "US",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("379.00"),
            "USD",
            16),
        new SeedHotel(
            "Hyatt Regency Maui Resort and Spa",
            "Lahaina",
            "US",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("389.00"),
            "USD",
            14),
        new SeedHotel(
            "OUTRIGGER Kā‘anapali Beach Resort",
            "Lahaina",
            "US",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("419.00"),
            "USD",
            12),
        new SeedHotel(
            "Royal Lahaina Resort & Bungalows",
            "Lahaina",
            "US",
            "Tropical resort steps from the sand with a pool, swim-up bar, and breezy patio rooms.",
            new BigDecimal("449.00"),
            "USD",
            10));
  }

  private record SeedHotel(
      String name,
      String city,
      String country,
      String description,
      BigDecimal nightlyRate,
      String currency,
      int availableRooms) {}
}
